Fix cl icd khr implementation
RJVB/ocl_icd_wrapper pull request #1
Opened 2023-09-19 14:12 UTC by Kerilk

This should allow ocl-icd to load the wrapper without any modification.
I couldn't test running it on Linux since I couldn't find a non ICD driver.
In order to build it I had to remove suffixes that should not have been there in the first place.

2023-09-20 10:51 UTC, RJVB requested changes
It looks like the crucial change from this commit (#183d9b6) is somehow undone by the subsequent one? Either way after I apply the "net" patch (https://github.com/RJVB/ocl_icd_wrapper/pull/1.patch) the resulting library still exports the `clGetPlatformInfo` function from `OpenCL.framework`.

2023-09-20 18:56 UTC, Kerilk commented
OK, I've added a CI to the repo, and can demonstrate that this works using a brew install of ocl-icd:
https://github.com/Kerilk/ocl_icd_wrapper/actions/runs/6252835744/job/16976947419
Here is the output of `clinfo` from the CI run:
```
 Number of platforms                               2
pocl warning: encountered incomplete implementation in /tmp/pocl-20230901-6926-1kre1mw/pocl-4.0/lib/CL/clGetDeviceInfo.c:95
  Platform Name                                   Apple
  Platform Vendor                                 Apple
  Platform Version                                OpenCL 1.2 (Aug 29 2022 02:56:50)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_icd
  Platform Extensions function suffix             oiw

  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 3.0 PoCL 4.0  Apple, Release, RELOC, SPIR, LLVM 16.0.6, SLEEF, DISTRO, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_pocl_content_size
  Platform Extensions with Version                cl_khr_icd                                                       0x400000 (1.0.0)
                                                  cl_pocl_content_size                                             0x400000 (1.0.0)
  Platform Numeric Version                        0xc00000 (3.0.0)
  Platform Extensions function suffix             POCL
  Platform Host timer resolution                  0ns

  Platform Name                                   Apple
Number of devices                                 1
  Device Name                                     Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  Device Vendor                                   Intel
  Device Vendor ID                                0xffffffff
  Device Version                                  OpenCL 1.2 
  Driver Version                                  1.1
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               3
  Max clock frequency                             3337MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1x1
  Max work group size                             1024
  Preferred work group size multiple (kernel)     1
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                                8 / 8       
    int                                                  4 / 4       
    long                                                 2 / 2       
    half                                                 0 / 0        (n/a)
    float                                                4 / 4       
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              15032385536 (14GiB)
  Error Correction support                        No
  Max memory allocation                           3758096384 (3.5GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        64
  Global Memory cache line size                   12582912 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            65536 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   1 bytes
    Pitch alignment for 2D image buffers          1 pixels
    Max 2D image size                             8192x8192 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4096 (4KiB)
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_APPLE_fp64_basic_ops cl_APPLE_fixed_alpha_channel_orders cl_APPLE_biased_fixed_point_image_formats cl_APPLE_command_queue_priority

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     cpu
  Device Vendor                                   Unknown x86
  Device Vendor ID                                0x6c636f70
  Device Version                                  OpenCL 3.0 PoCL HSTR: cpu-x86_64-apple-macosx11.0.0-ivybridge
  Device Numeric Version                          0xc00000 (3.0.0)
  Driver Version                                  4.0
  Device OpenCL C Version                         OpenCL C 1.2 PoCL
  Device OpenCL C all versions          [...]

2023-09-20 20:13 UTC, RJVB commented
Wow, you've been on a roll, it's going to take me some time to read through all this :) Thanks!

2023-09-20 20:35 UTC, Kerilk commented
> Wow, you've been on a roll, it's going to take me some time to read through all this :) Thanks!

I hope we can contribute this back to @jrprice, and I think the CI would help doing that.
There is a bit of cleanup that needs to be done beforehand though.

2023-09-20 22:34 UTC, RJVB commented
BTW, didn't you say you had no non-ICD OCL implementation on Linux? You could use Mesa's Clover for that (build with `-Dgallium-opencl=standalone`). I don't know on what kind of hardware that implementation is supposed to do something though; it doesn't give me any devices on my system.

2023-09-21 21:48 UTC, RJVB approved these changes

2023-09-21 21:49 UTC, merged

2023-09-21 21:49 UTC, RJVB commented
Thanks for all the work!

2023-09-21 21:58 UTC, RJVB commented
BTW:

```
ocl-icd(ocl_icd_loader.c:305): _get_function_addr: Function and symbol 'clGetPlatformInfo' have different addresses (0x1014c7ee0 != 0x7fff88d465d2)!
```

I completely overlooked the fact somehow that `_get_function_addr` checks both sources for a function...

2023-09-21 22:03 UTC, Kerilk commented
No problem, happy to help.



> BTW:
> 
> ```
> ocl-icd(ocl_icd_loader.c:305): _get_function_addr: Function and symbol 'clGetPlatformInfo' have different addresses (0x1014c7ee0 != 0x7fff88d465d2)!
> ```
> 
> I completely overlooked the fact somehow that `_get_function_addr` checks both sources for a function...

Yeas this is why this works. We have encountered some strange icds when we started this, as the loader and specification at first were not public. Vendors implemented their ICD in their own manner, and delivered their own version of the loader. Those were mostly incompatible with each other... So we created ocl_icd to be able to load all of them and create an open source reference implementation. So we had quite a bit of workaround to keep everybody playing nice. This is less of an issue nowadays.